book:
  title: "The Cosmic Game: A User's Guide to the Meaning of Life"
  subtitle: "The Ultimate Purpose of Human Experience"
  author: "Rez Khan"
  description: "The final revelation: why the elaborate game of human existence was designed, how consciousness evolves through incarnation, and what lies beyond graduation from Earth's cosmic university."
  keywords: ["consciousness", "spirituality", "meaning of life", "soul evolution", "metaphysics", "reincarnation"]
  language: "en"

build:
  source_dir: "src"
  output_dir: "output/final"

output:
  markdown:
    filename: "The_Cosmic_Game_Complete_Book.md"
  html:
    filename: "index.html"
    template: "book_template.html"

metadata:
  version: "3.0"
  last_updated: "2025-07-29"
  word_count_target: 90000
  
# Gap-based structure configuration
structure_type: "gap_based"
gap_increment: 10